config/routes.rb
Spree::Core::Engine.routes.append do

  namespace :admin do
    resource :pickpoint_regions
    resource :pickpoint_main
    resource :pickpoint_settings do
      collection do
        post :dismiss_alert
      end
    end  
    resources :orders do
      resource :pickpoint_delivery
    end
  end
  
  resources :pickpoints, :only => :show, :format => :json
  # Add your extension routes here
end

app/models/spree/pickpoint_region.rb
module Spree
  class PickpointRegion < ActiveRecord::Base
    
    attr_accessible :price, :name
    validates_uniqueness_of :name
    
    scope :priced, where('price > 0')
    has_many :pickpoints, foreign_key: :region, primary_key: :name
    
    def self.sync
      Pickpoint.all.map(&:region).uniq.each do |region|
        self.find_or_create_by_name(region)
      end
    end
    
    def self.prices
      price_sheet = {}
      self.priced.each do |region|
        price_sheet[region.name] = region.price
      end
      price_sheet
    end
    
  end
end

app/controllers/spree/admin/pickpoint_regions_controller.rb
module Spree
  module Admin
    class PickpointRegionsController < Spree::Admin::BaseController
      def show
        PickpointRegion.sync if params['refresh'].present? 
        @regions = PickpointRegion.all
      end
      
      def update
        ids = []
        prices = []
        params['price'].each do |id, price|
          ids << id
          prices << {:price => price}
        end
        PickpointRegion.update(ids, prices)
        redirect_to :action => 'show', :status => 302
      end
      
      # def update
        # params.each do |name, value|
          # next unless Spree::Config.has_preference? name
          # Spree::Config[name] = value
        # end
      # end
      
    end
  end
end

app/views/spree/admin/pickpoint_regions/show.html.erb
<%= render :partial => 'spree/admin/shared/pickpoint_sub_menu' %>

<h1><%= t(:pickpoint_regions) %> (<%= link_to t(:pickpoint_sync_regions), admin_pickpoint_regions_path(:refresh => 1) %>)</h1>

<%= form_tag(admin_pickpoint_regions_path, :method => :put) do %>
	<fieldset class="no-border-top">    
		<% @regions.select { |r| r.pickpoints.active.size > 0 || r.pickpoints.include?(pickpoint_home) }.each_with_index do |region, i| %>
	        <div class="field columns three <%= "alpha" if i % 5 == 0 || i == 0 %>  <%= "omega" if (i + 1) % 5 == 0 %>">
				<%= label :price, "#{region.name} - #{region.pickpoints.active.size}" %>
	        	<%= text_field :price, region.id, :value => region.price, :class => 'fullwidth'  %>
			</div>
	    <% end %>
		<div class="clear"></div>
		<div class="filter-actions actions" data-hook="admin_order_form_buttons">
			<%= button t(:update), 'icon-refresh' %>
		</div>
	</fieldset>
<% end %>